cout << '1' << '2' << '3' << endl;
cout << setw(15) << showpos << right << 4 << endl;
cout << setw(20) << internal << showpos << -67.09 << endl;
cout << setw(15) << right << showpos << 235 << endl;
cout << '8' << 'a' << '1' << endl;
cout << fixed << setprecision(2) << showpos << -121.0 << endl;
cout << setprecision(0) << showpos << 1 << 24 << endl;
cout << "String1\n" << "\tString2 \n" << " \t\t String3" << endl;
cout << "\tString1\n" << "String2" << endl;	
cout << noshowpos <<3 << '*' << "\tString\n1" << endl;
